/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin’s github repository:
https://github.com/kometenstaub/obsidian-version-history-diff
It is MIT-licensed:

	MIT License
	
	Copyright (c) 2022-2025 kometenstaub and contributors
	
	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
	

Other used code in this built file is licensed as follows:
	
This plugin uses diff2html:
https://github.com/rtfpessoa/diff2html

	Copyright 2014-2016 Rodrigo Fernandes https://rtfpessoa.github.io/

	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
	documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
	rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
	persons to whom the Software is furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
	Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
	WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
	COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
	OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


This plugin and diff2html use jsdiff:
https://github.com/kpdecker/jsdiff

	Software License Agreement (BSD License)
	
	Copyright (c) 2009-2015, Kevin Decker <kpdecker@gmail.com>
	
	All rights reserved.
	
	Redistribution and use of this software in source and binary forms, with or without modification,
	are permitted provided that the following conditions are met:
	
	* Redistributions of source code must retain the above
	  copyright notice, this list of conditions and the
	  following disclaimer.
	
	* Redistributions in binary form must reproduce the above
	  copyright notice, this list of conditions and the
	  following disclaimer in the documentation and/or other
	  materials provided with the distribution.
	
	* Neither the name of Kevin Decker nor the names of its
	  contributors may be used to endorse or promote products
	  derived from this software without specific prior
	  written permission.
	
	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
	IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
	FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
	CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
	DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
	DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
	IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
	OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
	
	
diff2html uses hogan.js:
https://github.com/twitter/hogan.js

                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "Legal Entity" shall mean the union of the acting entity and all
      other entities that control, are controlled by, or are under common
      control with that entity. For the purposes of this definition,
      "control" means (i) the power, direct or indirect, to cause the
      direction or management of such entity, whether by contract or
      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      outstanding shares, or (iii) beneficial ownership of such entity.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      "Source" form shall mean the preferred form for making modifications,
      including but not limited to software source code, documentation
      source, and configuration files.

      "Object" form shall mean any form resulting from mechanical
      transformation or translation of a Source form, including but
      not limited to compiled object code, generated documentation,
      and conversions to other media types.

      "Work" shall mean the work of authorship, whether in Source or
      Object form, made available under the License, as indicated by a
      copyright notice that is included in or attached to the work
      (an example is provided in the Appendix below).

      "Derivative Works" shall mean any work, whether in Source or Object
      form, that is based on (or derived from) the Work and for which the
      editorial revisions, annotations, elaborations, or other modifications
      represent, as a whole, an original work of authorship. For the purposes
      of this License, Derivative Works shall not include works that remain
      separable from, or merely link (or bind by name) to the interfaces of,
      the Work and Derivative Works thereof.

      "Contribution" shall mean any work of authorship, including
      the original version of the Work and any modifications or additions
      to that Work or Derivative Works thereof, that is intentionally
      submitted to Licensor for inclusion in the Work by the copyright owner
      or by an individual or Legal Entity authorized to submit on behalf of
      the copyright owner. For the purposes of this definition, "submitted"
      means any form of electronic, verbal, or written communication sent
      to the Licensor or its representatives, including but not limited to
      communication on electronic mailing lists, source code control systems,
      and issue tracking systems that are managed by, or on behalf of, the
      Licensor for the purpose of discussing and improving the Work, but
      excluding communication that is conspicuously marked or otherwise
      designated in writing by the copyright owner as "Not a Contribution."

      "Contributor" shall mean Licensor and any individual or Legal Entity
      on behalf of whom a Contribution has been received by Licensor and
      subsequently incorporated within the Work.

   2. Grant of Copyright License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      copyright license to reproduce, prepare Derivative Works of,
      publicly display, publicly perform, sublicense, and distribute the
      Work and such Derivative Works in Source or Object form.

   3. Grant of Patent License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      (except as stated in this section) patent license to make, have made,
      use, offer to sell, sell, import, and otherwise transfer the Work,
      where such license applies only to those patent claims licensable
      by such Contributor that are necessarily infringed by their
      Contribution(s) alone or by combination of their Contribution(s)
      with the Work to which such Contribution(s) was submitted. If You
      institute patent litigation against any entity (including a
      cross-claim or counterclaim in a lawsuit) alleging that the Work
      or a Contribution incorporated within the Work constitutes direct
      or contributory patent infringement, then any patent licenses
      granted to You under this License for that Work shall terminate
      as of the date such litigation is filed.

   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

      You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use, reproduction, or distribution of Your modifications, or
      for any such Derivative Works as a whole, provided Your use,
      reproduction, and distribution of the Work otherwise complies with
      the conditions stated in this License.

   5. Submission of Contributions. Unless You explicitly state otherwise,
      any Contribution intentionally submitted for inclusion in the Work
      by You to the Licensor shall be under the terms and conditions of
      this License, without any additional terms or conditions.
      Notwithstanding the above, nothing herein shall supersede or modify
      the terms of any separate license agreement you may have executed
      with Licensor regarding such Contributions.

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

   7. Disclaimer of Warranty. Unless required by applicable law or
      agreed to in writing, Licensor provides the Work (and each
      Contributor provides its Contributions) on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
      implied, including, without limitation, any warranties or conditions
      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
      PARTICULAR PURPOSE. You are solely responsible for determining the
      appropriateness of using or redistributing the Work and assume any
      risks associated with Your exercise of permissions under this License.

   8. Limitation of Liability. In no event and under no legal theory,
      whether in tort (including negligence), contract, or otherwise,
      unless required by applicable law (such as deliberate and grossly
      negligent acts) or agreed to in writing, shall any Contributor be
      liable to You for damages, including any direct, indirect, special,
      incidental, or consequential damages of any character arising as a
      result of this License or out of the use or inability to use the
      Work (including but not limited to damages for loss of goodwill,
      work stoppage, computer failure or malfunction, or any and all
      other commercial damages or losses), even if such Contributor
      has been advised of the possibility of such damages.

   9. Accepting Warranty or Additional Liability. While redistributing
      the Work or Derivative Works thereof, You may choose to offer,
      and charge a fee for, acceptance of support, warranty, indemnity,
      or other liability obligations and/or rights consistent with this
      License. However, in accepting such obligations, You may act only
      on Your own behalf and on Your sole responsibility, not on behalf
      of any other Contributor, and only if You agree to indemnify,
      defend, and hold each Contributor harmless for any liability
      incurred by, or claims asserted against, such Contributor by reason
      of your accepting any such warranty or additional liability.

   END OF TERMS AND CONDITIONS

hogan.js uses nopt:
https://github.com/npm/nopt

	The ISC License
	
	Copyright (c) Isaac Z. Schlueter and Contributors
	
	Permission to use, copy, modify, and/or distribute this software for any
	purpose with or without fee is hereby granted, provided that the above
	copyright notice and this permission notice appear in all copies.
	
	THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
	WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
	MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
	ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
	WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
	ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
	IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

nopt uses abbrev:
https://github.com/npm/abbrev-js

	This software is dual-licensed under the ISC and MIT licenses.
	You may use this software under EITHER of the following licenses.
	
	----------
	
	The ISC License
	
	Copyright (c) Isaac Z. Schlueter and Contributors
	
	Permission to use, copy, modify, and/or distribute this software for any
	purpose with or without fee is hereby granted, provided that the above
	copyright notice and this permission notice appear in all copies.
	
	THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
	WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
	MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
	ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
	WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
	ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
	IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
	

hogan.js uses mkdirp:
https://github.com/isaacs/node-mkdirp

	Copyright (c) 2011-2022 James Halliday (mail@substack.net) and Isaac Z. Schlueter (i@izs.me)
	
	This project is free software released under the MIT license:
	
	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.
	
*/

var i=`/* unminified CSS, MIT-licensed from diff2html, with changes from @kometenstaub for the modals
and adaptation to Obsidian variables and colour changes in addition to the colour-blind
mode from @SlRvb, which fall under the same license (MIT license, @kometenstaub and contributors)

	Original license:

	https://github.com/rtfpessoa/diff2html/blob/master/LICENSE.md

	Copyright 2014-2016 Rodrigo Fernandes https://rtfpessoa.github.io/

	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
	documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
	rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
	persons to whom the Software is furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
	Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
	WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
	COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
	OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

*/

.theme-dark,
.theme-light {
	--sync-delete-bg: #ff475040;
	--sync-delete-hl: #96050a75;
	--sync-insert-bg: #68d36840;
	--sync-insert-hl: #23c02350;
	--sync-change-bg: #ffd55840;
	--sync-selected: #3572b0;

	--sync-delete: #c33;
	--sync-insert: #399839;
	--sync-change: #d0b44c;
	--sync-move: #3572b0;
}

.is-mobile {
	.modal.mod-sync-history.diff .modal-content > * {
		width: unset;
		height: unset;
		position: unset;
		max-height: 100%;
	}

	.diff {
		.modal-content {
			flex-direction: unset;
		}
		.sync-history-list-container {
			flex-direction: column;

			button.mod-cta {
				margin-left: -0.25em;
			}
		}
		.sync-history-list-item-header.is-active {
			background-color: var(--background-primary-alt);
		}
	}
	.sync-history-content-container.diff {
		width: 70vw !important;
	}
}

/* needed for iOS */
.is-ios.is-mobile {
	.diff {
		.sync-history-content-container.diff {
			.d2h-code-linenumber {
				position: relative;
			}
			.d2h-code-line {
				padding-left: 0.5em;
			}
		}
	}
}

.diff {
	.d2h-d-none {
		display: none;
	}
	.d2h-wrapper {
		text-align: left;
		border-radius: 0.25em;
		overflow: auto;
	}
	.d2h-file-header.d2h-file-header {
		background-color: var(--background-secondary);
		border-bottom: 1px solid var(--background-modifier-border);
		font-family: Source Sans Pro, Helvetica Neue, Helvetica, Arial,
			sans-serif;
		height: 35px;
		padding: 5px 10px;
	}
	.d2h-file-header,
	.d2h-file-stats {
		display: -webkit-box;
		display: -ms-flexbox;
		display: flex;
	}
	.d2h-file-header {
		display: none;
	}
	.d2h-file-stats {
		font-size: 14px;
		margin-left: auto;
	}
	.d2h-lines-added {
		border: 1px solid var(--color-green);
		border-radius: 5px 0 0 5px;
		color: var(--color-green);
		padding: 2px;
		text-align: right;
		vertical-align: middle;
	}
	.d2h-lines-deleted {
		border: 1px solid var(--color-red);
		border-radius: 0 5px 5px 0;
		color: var(--color-red);
		margin-left: 1px;
		padding: 2px;
		text-align: left;
		vertical-align: middle;
	}
	.d2h-file-name-wrapper {
		-webkit-box-align: center;
		-ms-flex-align: center;
		align-items: center;
		display: -webkit-box;
		display: -ms-flexbox;
		display: flex;
		font-size: 15px;
		width: 100%;
	}
	.d2h-file-name {
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		color: var(--text-normal);
		font-size: var(--h5-size);
	}
	.d2h-file-wrapper {
		border: 1px solid var(--background-secondary-alt);
		border-radius: 3px;
		margin-bottom: 1em;
		max-height: 100%;
	}
	.d2h-file-collapse {
		-webkit-box-pack: end;
		-ms-flex-pack: end;
		-webkit-box-align: center;
		-ms-flex-align: center;
		align-items: center;
		border: 1px solid var(--background-secondary-alt);
		border-radius: 3px;
		cursor: pointer;
		display: none;
		font-size: 12px;
		justify-content: flex-end;
		padding: 4px 8px;
	}
	.d2h-file-collapse.d2h-selected {
		background-color: var(--sync-selected);
	}
	.d2h-file-collapse-input {
		margin: 0 4px 0 0;
	}
	.d2h-diff-table {
		border-collapse: collapse;
		font-family: Menlo, Consolas, monospace;
		font-size: 13px;
		width: 100%;
	}
	.d2h-files-diff {
		width: 100%;
	}
	.d2h-file-diff {
		/*
		overflow-y: scroll;
		*/
		border-radius: 5px;
	}
	.d2h-file-side-diff {
		display: inline-block;
		margin-bottom: -8px;
		margin-right: -4px;
		overflow-x: scroll;
		overflow-y: hidden;
		width: 50%;
	}
	.d2h-code-line {
		padding-left: 6em;
		padding-right: 1.5em;
	}
	.d2h-code-line,
	.d2h-code-side-line {
		display: inline-block;
		-webkit-user-select: none;
		-moz-user-select: none;
		-ms-user-select: none;
		user-select: none;
		white-space: nowrap;
		width: 100%;
	}
	.d2h-code-side-line {
		/* needed to be changed */
		padding-left: 0.5em;
		padding-right: 0.5em;
	}
	.d2h-code-line-ctn {
		word-wrap: normal;
		background: none;
		display: inline-block;
		padding: 0;
		-webkit-user-select: text;
		-moz-user-select: text;
		-ms-user-select: text;
		user-select: text;
		vertical-align: middle;
		width: 100%;
		/* only works for line-by-line */
		white-space: pre-wrap;
	}
	.d2h-code-line del,
	.d2h-code-side-line del {
		background-color: var(--sync-delete-hl);
		color: var(--text-normal);
	}
	.d2h-code-line del,
	.d2h-code-line ins,
	.d2h-code-side-line del,
	.d2h-code-side-line ins {
		border-radius: 0.2em;
		display: inline-block;
		margin-top: -1px;
		text-decoration: none;
		vertical-align: middle;
	}
	.d2h-code-line ins,
	.d2h-code-side-line ins {
		background-color: var(--sync-insert-hl);
		text-align: left;
	}
	.d2h-code-line-prefix {
		word-wrap: normal;
		background: none;
		display: inline;
		padding: 0;
		white-space: pre;
	}
	.line-num1 {
		float: left;
	}
	.line-num1,
	.line-num2 {
		-webkit-box-sizing: border-box;
		box-sizing: border-box;
		overflow: hidden;
		/*
		padding: 0 0.5em;
		*/
		text-overflow: ellipsis;
		width: 2.5em;
		padding-left: 0;
	}
	.line-num2 {
		float: right;
	}
	.d2h-code-linenumber {
		background-color: var(--background-primary);
		border: solid var(--background-modifier-border);
		border-width: 0 1px;
		-webkit-box-sizing: border-box;
		box-sizing: border-box;
		color: var(--text-faint);
		cursor: pointer;
		display: inline-block;
		position: absolute;
		text-align: right;
		width: 5.5em;
	}
	.d2h-code-linenumber:after {
		content: '\\200b';
	}
	.d2h-code-side-linenumber {
		background-color: var(--background-primary);
		border: solid var(--background-modifier-border);
		border-width: 0 1px;
		-webkit-box-sizing: border-box;
		box-sizing: border-box;
		color: var(--text-faint);
		cursor: pointer;
		overflow: hidden;
		padding: 0 0.5em;
		text-align: right;
		text-overflow: ellipsis;
		width: 4em;
		/* needed to be changed */
		display: table-cell;
		position: relative;
	}
	.d2h-code-side-linenumber:after {
		content: '\\200b';
	}
	.d2h-code-side-emptyplaceholder,
	.d2h-emptyplaceholder {
		background-color: var(--background-primary);
		border-color: var(--background-modifier-border);
	}
	.d2h-code-line-prefix,
	.d2h-code-linenumber,
	.d2h-code-side-linenumber,
	.d2h-emptyplaceholder {
		-webkit-user-select: none;
		-moz-user-select: none;
		-ms-user-select: none;
		user-select: none;
	}
	.d2h-code-linenumber,
	.d2h-code-side-linenumber {
		direction: rtl;
	}
	.d2h-del {
		background-color: var(--sync-delete-bg);
		border-color: var(--sync-delete-hl);
	}
	.d2h-ins {
		background-color: var(--sync-insert-bg);
		border-color: var(--sync-insert-hl);
	}
	.d2h-info {
		background-color: var(--background-primary);
		border-color: var(--background-modifier-border);
		color: var(--text-faint);
	}
	.d2h-del,
	.d2h-ins,
	.d2h-file-diff .d2h-change {
		color: var(--text-normal);
	}
	.d2h-file-diff .d2h-del.d2h-change {
		background-color: var(--sync-change-bg);
	}
	.d2h-file-diff .d2h-ins.d2h-change {
		background-color: var(--sync-insert-bg);
	}
	.d2h-file-list-wrapper {
		a {
			text-decoration: none;
			cursor: default;
			-webkit-user-drag: none;
		}

		svg {
			display: none;
		}
	}
	.d2h-file-list-header {
		text-align: left;
	}
	.d2h-file-list-title {
		display: none;
	}
	.d2h-file-list-line {
		display: -webkit-box;
		display: -ms-flexbox;
		display: flex;
		text-align: left;
	}
	.d2h-file-list {
	}
	.d2h-file-list > li {
		border-bottom: 1px solid var(--background-modifier-border);
		margin: 0;
		padding: 5px 10px;
	}
	.d2h-file-list > li:last-child {
		border-bottom: none;
	}
	.d2h-file-switch {
		cursor: pointer;
		display: none;
		font-size: 10px;
	}
	.d2h-icon {
		fill: currentColor;
		margin-right: 10px;
		vertical-align: middle;
	}
	.d2h-deleted {
		color: var(--sync-delete);
	}
	.d2h-added {
		color: var(--sync-insert);
	}
	.d2h-changed {
		color: var(--sync-change);
	}
	.d2h-moved {
		color: var(--sync-move);
	}
	.d2h-tag {
		background-color: var(--background-secondary);
		display: -webkit-box;
		display: -ms-flexbox;
		display: flex;
		font-size: 10px;
		margin-left: 5px;
		padding: 0 2px;
	}
	.d2h-deleted-tag {
		border: 1px solid var(--sync-delete);
	}
	.d2h-added-tag {
		border: 1px solid var(--sync-insert);
	}
	.d2h-changed-tag {
		border: 1px solid var(--sync-change);
	}
	.d2h-moved-tag {
		border: 1px solid var(--sync-move);
	}

	/* needed for line-by-line*/

	.d2h-diff-tbody {
		position: relative;
	}

	.sync-history-content-container {
		/*max-width: 11vw;*/
		padding: 0.5rem;
		border-radius: 0.25em;
	}

	.sync-history-list-container {
		flex-shrink: unset;

		button.mod-cta {
			margin-left: 0.5em;
			margin-right: 0.5em;
			margin-top: 0.5em;

			+ .sync-history-list.sync-history-list {
				margin-top: 0em;
			}
		}

		.sync-history-list {
			margin-top: 1.5em;

			.sync-history-list-item-header {
				border-radius: 0.25em;
				display: block;
			}
		}
	}

	.modal-content {
		display: flex;
		flex-direction: row;
		height: 80vh;
	}
}

/* CSS settings needed for modal */

.modal.mod-sync-history.diff {
	min-width: 95vw;
	max-height: 90vh;

	.sync-history-list-item-header.is-active:hover {
		background-color: var(--interactive-accent-hover);
	}
}
@media only screen and (min-width: 1200px) {
	.modal.mod-sync-history.diff {
		min-width: 80vw;
	}
}

/*Color-Blind Mode*/

.theme-dark {
	.colorblind {
		.d2h-code-line del {
			background: repeating-linear-gradient(
				-45deg,
				var(--background-primary),
				var(--sync-delete-hl) 2px,
				var(--sync-delete-hl) 2px,
				var(--sync-delete-hl) 19px
			);
		}

		.d2h-ins:not(.d2h-code-linenumber) {
			background-image: radial-gradient(
					var(--sync-insert-hl) 2px,
					transparent 1px
				),
				radial-gradient(var(--sync-insert-hl) 2px, transparent 1px);
		}
	}
}

.colorblind {
	.d2h-code-line del,
	.d2h-del:not(.d2h-change):not(.d2h-code-linenumber) {
		background: repeating-linear-gradient(
			-45deg,
			transparent,
			var(--sync-delete-bg) 2px,
			var(--sync-delete-bg) 2px,
			var(--sync-delete-bg) 19px
		);
	}

	.d2h-ins:not(.d2h-code-linenumber) {
		background-image: radial-gradient(
				var(--background-primary) 2px,
				transparent 1px
			),
			radial-gradient(var(--background-primary) 2px, transparent 1px);
		background-size: 40px 40px;
		background-position: 0 0, 25px 28px;
	}

	.d2h-code-linenumber.d2h-ins,
	.d2h-code-line ins {
		border-style: solid;
		border-color: var(--sync-insert);
		border-width: 1px 2px;
	}
}

/* fix modal height */

.version-display {
	.modal {
		max-height: 90vh;

		/* show YAML which Obsidian Properties hides otherwise */
		.frontmatter.language-yaml {
			display: block !important;
		}
		.language-yaml:after {
			display: none;
		}

		.restore {
			margin-right: 1em;
		}

		/* for textarea that displays plain text version */

		textarea.plain-text-area {
			/*
			max-width: 60vw;
			min-width: 60vw;
			*/
			height: 67vh;
			margin-top: 1rem;
			position: inherit;
			min-width: 100%;
		}
	}

	@media only screen and (max-width: 1000px) {
		.modal {
			min-width: 90vw;
		}
	}

	@media only screen and (min-width: 1001px) {
		.modal {
			max-width: 80vw;
		}
	}
	@media only screen and (min-width: 1200px) {
		.modal {
			max-width: 70vw;
		}
	}

	@media only screen and (min-width: 1400px) {
		.modal {
			max-width: 65vw;
		}
	}
}

.binary-diff {
	display: flex;
	flex-direction: row;
	gap: 1.5rem;
	width: 100%;
	height: 100%;
	min-height: 400px;
	overflow: auto;

	.binary-side {
		flex: 1;
		display: flex;
		flex-direction: column;
		align-items: center;
		padding: 1.5rem;
		border: 1px solid var(--background-modifier-border);
		border-radius: 8px;
		background-color: var(--background-primary-alt);
		box-shadow: inset 0 0 10px rgba(0, 0, 0, 0.05);

		h4 {
			margin-top: 0;
			margin-bottom: 1rem;
			color: var(--text-normal);
			font-weight: 600;
		}

		img {
			max-width: 100%;
			max-height: 60vh;
			object-fit: contain;
			box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
			border-radius: 4px;
			background: repeating-conic-gradient(#555 0% 25%, #666 0% 50%) 50% /
				20px 20px;
		}

		.binary-fallback-msg {
			flex: 1;
			display: flex;
			align-items: center;
			justify-content: center;
			text-align: center;
			color: var(--text-muted);
			font-style: italic;
			margin-bottom: 1rem;
			padding: 2rem;
			border: 2px dashed var(--background-modifier-border);
			border-radius: 6px;
			width: 100%;
			max-width: 300px;
		}
	}
}

.diff-toggle-bar {
	display: flex;
	justify-content: center;
	gap: 0.5rem;
	padding: 0.5rem;
	background-color: var(--background-secondary);
	border-bottom: 1px solid var(--background-modifier-border);
	width: 100%;

	.diff-toggle-btn {
		padding: 0.25rem 0.75rem;
		border-radius: 4px;
		border: 1px solid var(--background-modifier-border);
		background-color: var(--background-primary);
		color: var(--text-muted);
		cursor: pointer;
		font-size: var(--font-small);
		transition: background-color 0.2s, color 0.2s;

		&:hover {
			background-color: var(--background-primary-alt);
			color: var(--text-normal);
		}

		&.is-active {
			background-color: var(--interactive-accent);
			color: var(--text-on-accent);
			border-color: var(--interactive-accent);
		}
	}
}

.sync-history-middle-container {
	display: flex;
	flex-direction: column;
	flex-grow: 1;
	height: 100%;
	overflow: hidden;
}

.markdown-rendered-diff {
	display: flex;
	flex-direction: row;
	gap: 1.5rem;
	width: 100%;
	height: 100%;
	overflow: auto;

	.markdown-side {
		flex: 1;
		display: flex;
		flex-direction: column;
		padding: 1.5rem;
		border: 1px solid var(--background-modifier-border);
		border-radius: 8px;
		background-color: var(--background-primary);
		box-shadow: inset 0 0 10px rgba(0, 0, 0, 0.02);
		overflow: auto;

		h4 {
			margin-top: 0;
			margin-bottom: 1rem;
			color: var(--text-normal);
			font-weight: 600;
			border-bottom: 1px solid var(--background-modifier-border);
			padding-bottom: 0.5rem;
		}

		.rendered-content {
			flex: 1;
			color: var(--text-normal);
			line-height: 1.6;
			font-size: var(--font-normal);

			p {
				margin-bottom: 1em;
			}
		}
	}
}
`;
